name: async_extension
description: Dart async extensions, to help usage of Future, FutureOr and async methods.
version: 1.0.0
homepage: https://github.com/eneural-net/async_extension

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.9
  dependency_validator: ^3.1.0
  test_cov: ^1.0.1