name: async_extension
description: Dart async extensions, to help usage of Future, FutureOr and async methods. Also allows performance improvements when using sync and async code.
version: 1.1.1
homepage: https://github.com/eneural-net/async_extension

environment:
  sdk: '>=2.18.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3
  dependency_validator: ^3.2.2
  coverage: ^1.6.3
