name: async_extension
description: Dart async extensions, to help usage of Future, FutureOr and async methods. Also allows performance improvements when using sync and async code.
version: 1.0.12
homepage: https://github.com/eneural-net/async_extension

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.12
  dependency_validator: ^3.2.2
  coverage: ^1.0.4
