name: async_extension
description: Dart async extensions, to help usage of Future, FutureOr and async methods. Also allows performance improvements when using sync and async code.
version: 1.2.13
homepage: https://github.com/eneural-net/async_extension

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.13
  dependency_validator: ^4.1.2
  coverage: ^1.11.1
